global:
  all:
    namespace: dev

  checkoutservice: 
    service: 
        port: 5050

  
replicaCount: 1
image:
  repository: 13s10/checkoutservice
ports:
  containerPort: 5050
readiness:
  command: ["/bin/grpc_health_probe", "-addr=:5050"]
liveness:
  command: ["/bin/grpc_health_probe", "-addr=:5050"]


service:
  type: ClusterIP
resources: 
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

configmap:
  data:
    PORT: "5050"
    PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
    SHIPPING_SERVICE_ADDR: "shippingservice:50051"
    PAYMENT_SERVICE_ADDR: "paymentservice:50051"
    EMAIL_SERVICE_ADDR: "emailservice:5000"
    CURRENCY_SERVICE_ADDR: "currencyservice:7000"
    CART_SERVICE_ADDR: "cartservice:7070"
