apiVersion: v1
kind: Service
metadata:
  name: {{ include "paymentservice.fullname" . }}
spec:
  type: {{ .Values.global.paymentservice.service.type }}
  ports:
    - port: {{ .Values.global.paymentservice.service.port }}
      targetPort: {{ .Values.global.paymentservice.service.port }}
      name: http
  selector:
    {{- include "paymentservice.selectorLabels" . | nindent 4 }}
