apiVersion: v1
kind: Service
metadata:
  name: {{ include "emailservice.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.emailservice.service.port }}
      targetPort: {{ .Values.global.emailservice.service.targetPort }}
      name: http
  selector:
    {{- include "emailservice.selectorLabels" . | nindent 4 }}
