global:
  all:
    namespace: dev

  adservice: 
    service: 
        port: 9555

  
replicaCount: 1
image:
  repository: 13s10/adservice
ports:
  containerPort: 9555
readiness:
  command: ["/bin/grpc_health_probe", "-addr=:9555"]
liveness:
  command: ["/bin/grpc_health_probe", "-addr=:9555"]

serviceAccountName: default

service:
  type: ClusterIP
resources: 
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 180Mi

configmap:
  data:
    PORT: "9555"
