apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.frontend.service.port }}
      targetPort: {{ .Values.global.frontend.service.targetPort }}
      name: http
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}

---
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
spec:
  type: {{ .Values.service.type2 }}
  ports:
    - port: {{ .Values.global.frontend.service.port }}
      targetPort: {{ .Values.global.frontend.service.targetPort }}
      name: http
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}