apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recommendationservice.fullname" . }}
data:
  {{- range $key, $val := .Values.configmap.data }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}
