apiVersion: v1
kind: Service
metadata:
  name: {{ include "shippingservice.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.shippingservice.service.port }}
      targetPort: {{ .Values.global.shippingservice.service.port }}
      name: http
  selector:
    {{- include "shippingservice.selectorLabels" . | nindent 4 }}
