apiVersion: v1
kind: Service
metadata:
  name: {{ include "productcatalogservice.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.productcatalogservice.service.port }}
      targetPort: {{ .Values.global.productcatalogservice.service.port }}
      name: http
  selector:
    {{- include "productcatalogservice.selectorLabels" . | nindent 4 }}
